site_name: Polly
site_url: https://github.com/emccode/polly
repo_url: https://github.com/emccode/polly.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs/.themes/yeti
#site_favicon: favicon.png

pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
